// Turkish administrative data: Cities (İller) → Districts (İlçeler) → Neighbourhoods (Mahalleler)

export const TURKEY_CITIES: string[] = [
  "Adana", "Adıyaman", "Afyonkarahisar", "Ağrı", "Aksaray", "Amasya", "Ankara",
  "Antalya", "Ardahan", "Artvin", "Aydın", "Balıkesir", "Bartın", "Batman",
  "Bayburt", "Bilecik", "Bingöl", "Bitlis", "Bolu", "Burdur", "Bursa",
  "Çanakkale", "Çankırı", "Çorum", "Denizli", "Diyarbakır", "Düzce", "Edirne",
  "Elazığ", "Erzincan", "Erzurum", "Eskişehir", "Gaziantep", "Giresun",
  "Gümüşhane", "Hakkari", "Hatay", "Iğdır", "Isparta", "İstanbul", "İzmir",
  "Kahramanmaraş", "Karabük", "Karaman", "Kars", "Kastamonu", "Kayseri",
  "Kilis", "Kırıkkale", "Kırklareli", "Kırşehir", "Kocaeli", "Konya",
  "Kütahya", "Malatya", "Manisa", "Mardin", "Mersin", "Muğla", "Muş",
  "Nevşehir", "Niğde", "Ordu", "Osmaniye", "Rize", "Sakarya", "Samsun",
  "Siirt", "Sinop", "Sivas", "Şanlıurfa", "Şırnak", "Tekirdağ", "Tokat",
  "Trabzon", "Tunceli", "Uşak", "Van", "Yalova", "Yozgat", "Zonguldak",
];

export const TURKEY_DISTRICTS: Record<string, string[]> = {
  "Adana": ["Aladağ", "Ceyhan", "Çukurova", "Feke", "İmamoğlu", "Karaisalı", "Karataş", "Kozan", "Pozantı", "Saimbeyli", "Sarıçam", "Seyhan", "Tufanbeyli", "Yumurtalık", "Yüreğir"],
  "Adıyaman": ["Besni", "Çelikhan", "Gerger", "Gölbaşı", "Kahta", "Merkez", "Samsat", "Sincik", "Tut"],
  "Afyonkarahisar": ["Başmakçı", "Bayat", "Bolvadin", "Çay", "Çobanlar", "Dazkırı", "Dinar", "Emirdağ", "Evciler", "Hocalar", "İhsaniye", "İscehisar", "Kızılören", "Merkez", "Sandıklı", "Sinanpaşa", "Sultandağı", "Şuhut"],
  "Ağrı": ["Diyadin", "Doğubayazıt", "Eleşkirt", "Hamur", "Merkez", "Patnos", "Taşlıçay", "Tutak"],
  "Aksaray": ["Ağaçören", "Eskil", "Gülağaç", "Güzelyurt", "Merkez", "Ortaköy", "Sarıyahşi", "Sultanhanı"],
  "Amasya": ["Göynücek", "Gümüşhacıköy", "Hamamözü", "Merkez", "Merzifon", "Suluova", "Taşova"],
  "Ankara": ["Altındağ", "Ayaş", "Balâ", "Beypazarı", "Çamlıdere", "Çankaya", "Çubuk", "Elmadağ", "Etimesgut", "Evren", "Gölbaşı", "Güdül", "Haymana", "Kalecik", "Kazan", "Keçiören", "Kızılcahamam", "Mamak", "Nallıhan", "Polatlı", "Pursaklar", "Sincan", "Şereflikoçhisar", "Yenimahalle"],
  "Antalya": ["Akseki", "Aksu", "Alanya", "Demre", "Döşemealtı", "Elmalı", "Finike", "Gazipaşa", "Gündoğmuş", "İbradı", "Kaş", "Kemer", "Kepez", "Konyaaltı", "Korkuteli", "Kumluca", "Manavgat", "Muratpaşa", "Serik"],
  "Ardahan": ["Çıldır", "Damal", "Göle", "Hanak", "Merkez", "Posof"],
  "Artvin": ["Ardanuç", "Arhavi", "Borçka", "Hopa", "Kemalpaşa", "Merkez", "Murgul", "Şavşat", "Yusufeli"],
  "Aydın": ["Bozdoğan", "Buharkent", "Çine", "Didim", "Efeler", "Germencik", "İncirliova", "Karacasu", "Karpuzlu", "Koçarlı", "Köşk", "Kuşadası", "Kuyucak", "Nazilli", "Söke", "Sultanhisar", "Yenipazar"],
  "Balıkesir": ["Altıeylül", "Ayvalık", "Balya", "Bandırma", "Bigadiç", "Burhaniye", "Dursunbey", "Edremit", "Erdek", "Gömeç", "Gönen", "Havran", "İvrindi", "Karesi", "Kepsut", "Manyas", "Marmara", "Savaştepe", "Sındırgı", "Susurluk"],
  "Bartın": ["Amasra", "Kurucaşile", "Merkez", "Ulus"],
  "Batman": ["Beşiri", "Gercüş", "Hasankeyf", "Kozluk", "Merkez", "Sason"],
  "Bayburt": ["Aydıntepe", "Demirözü", "Merkez"],
  "Bilecik": ["Bozüyük", "Gölpazarı", "İnhisar", "Merkez", "Osmaneli", "Pazaryeri", "Söğüt", "Yenipazar"],
  "Bingöl": ["Adaklı", "Genç", "Karlıova", "Kiğı", "Merkez", "Solhan", "Yayladere", "Yedisu"],
  "Bitlis": ["Adilcevaz", "Ahlat", "Güroymak", "Hizan", "Merkez", "Mutki", "Tatvan"],
  "Bolu": ["Dörtdivan", "Gerede", "Göynük", "Kıbrıscık", "Mengen", "Merkez", "Mudurnu", "Seben", "Yeniçağa"],
  "Burdur": ["Altınyayla", "Bucak", "Çavdır", "Çeltikçi", "Gölhisar", "Karamanlı", "Kemer", "Merkez", "Tefenni", "Yeşilova"],
  "Bursa": ["Büyükorhan", "Gemlik", "Gürsu", "Harmancık", "İnegöl", "İznik", "Karacabey", "Keles", "Kestel", "Mudanya", "Mustafakemalpaşa", "Nilüfer", "Orhaneli", "Orhangazi", "Osmangazi", "Yenişehir", "Yıldırım"],
  "Çanakkale": ["Ayvacık", "Bayramiç", "Biga", "Bozcaada", "Çan", "Eceabat", "Ezine", "Gelibolu", "Gökçeada", "Lapseki", "Merkez", "Yenice"],
  "Çankırı": ["Atkaracalar", "Bayramören", "Çerkeş", "Eldivan", "Ilgaz", "Kızılırmak", "Korgun", "Kurşunlu", "Merkez", "Orta", "Şabanözü", "Yapraklı"],
  "Çorum": ["Alaca", "Bayat", "Boğazkale", "Dodurga", "İskilip", "Kargı", "Laçin", "Mecitözü", "Merkez", "Oğuzlar", "Ortaköy", "Osmancık", "Sungurlu", "Uğurludağ"],
  "Denizli": ["Acıpayam", "Babadağ", "Baklan", "Bekilli", "Beyağaç", "Bozkurt", "Buldan", "Çal", "Çameli", "Çardak", "Çivril", "Güney", "Honaz", "Kale", "Merkezefendi", "Pamukkale", "Sarayköy", "Serinhisar", "Tavas"],
  "Diyarbakır": ["Bağlar", "Bismil", "Çermik", "Çınar", "Çüngüş", "Dicle", "Eğil", "Ergani", "Hani", "Hazro", "Kayapınar", "Kocaköy", "Kulp", "Lice", "Silvan", "Sur", "Yenişehir"],
  "Düzce": ["Akçakoca", "Cumayeri", "Çilimli", "Gölyaka", "Gümüşova", "Gölyaka", "Kaynaşlı", "Merkez", "Yığılca"],
  "Edirne": ["Enez", "Havsa", "İpsala", "Keşan", "Lalapaşa", "Meriç", "Merkez", "Süloğlu", "Uzunköprü"],
  "Elazığ": ["Ağın", "Alacakaya", "Arıcak", "Baskil", "Karakoçan", "Keban", "Kovancılar", "Maden", "Merkez", "Palu", "Sivrice"],
  "Erzincan": ["Çayırlı", "İliç", "Kemah", "Kemaliye", "Merkez", "Otlukbeli", "Refahiye", "Tercan", "Üzümlü"],
  "Erzurum": ["Aşkale", "Aziziye", "Çat", "Hınıs", "Horasan", "İspir", "Karaçoban", "Karayazı", "Köprüköy", "Narman", "Oltu", "Olur", "Palandöken", "Pasinler", "Pazaryolu", "Şenkaya", "Tekman", "Tortum", "Uzundere", "Yakutiye"],
  "Eskişehir": ["Alpu", "Beylikova", "Çifteler", "Günyüzü", "Han", "İnönü", "Mahmudiye", "Mihalgazi", "Mihallıçcık", "Odunpazarı", "Sarıcakaya", "Seyitgazi", "Sivrihisar", "Tepebaşı"],
  "Gaziantep": ["Araban", "İslahiye", "Karkamış", "Nizip", "Nurdağı", "Oğuzeli", "Şahinbey", "Şehitkamil", "Yavuzeli"],
  "Giresun": ["Alucra", "Bulancak", "Çamoluk", "Çanakçı", "Dereli", "Doğankent", "Espiye", "Eynesil", "Görele", "Güce", "Keşap", "Merkez", "Piraziz", "Şebinkarahisar", "Tirebolu", "Yağlıdere"],
  "Gümüşhane": ["Kelkit", "Köse", "Kürtün", "Merkez", "Şiran", "Torul"],
  "Hakkari": ["Çukurca", "Derecik", "Merkez", "Şemdinli", "Yüksekova"],
  "Hatay": ["Altınözü", "Antakya", "Arsuz", "Belen", "Defne", "Dörtyol", "Erzin", "Hassa", "İskenderun", "Kırıkhan", "Kumlu", "Payas", "Reyhanlı", "Samandağ", "Yayladağı"],
  "Iğdır": ["Aralık", "Karakoyunlu", "Merkez", "Tuzluca"],
  "Isparta": ["Aksu", "Atabey", "Eğirdir", "Gelendost", "Gönen", "Keçiborlu", "Merkez", "Senirkent", "Sütçüler", "Şarkikaraağaç", "Uluborlu", "Yalvaç", "Yenişarbademli"],
  "İstanbul": ["Adalar", "Arnavutköy", "Ataşehir", "Avcılar", "Bağcılar", "Bahçelievler", "Bakırköy", "Başakşehir", "Bayrampaşa", "Beşiktaş", "Beykoz", "Beylikdüzü", "Beyoğlu", "Büyükçekmece", "Çatalca", "Çekmeköy", "Esenler", "Esenyurt", "Eyüpsultan", "Fatih", "Gaziosmanpaşa", "Güngören", "Kadıköy", "Kağıthane", "Kartal", "Küçükçekmece", "Maltepe", "Pendik", "Sancaktepe", "Sarıyer", "Şile", "Şişli", "Silivri", "Sultangazi", "Sultanbeyli", "Tuzla", "Ümraniye", "Üsküdar", "Zeytinburnu"],
  "İzmir": ["Aliağa", "Balçova", "Bayındır", "Bayraklı", "Bergama", "Beydağ", "Bornova", "Buca", "Çeşme", "Çiğli", "Dikili", "Foça", "Gaziemir", "Güzelbahçe", "Karabağlar", "Karaburun", "Karşıyaka", "Kemalpaşa", "Kınık", "Kiraz", "Konak", "Menderes", "Menemen", "Narlıdere", "Ödemiş", "Seferihisar", "Selçuk", "Tire", "Torbalı", "Urla"],
  "Kahramanmaraş": ["Afşin", "Andırın", "Çağlayancerit", "Dulkadiroğlu", "Ekinözü", "Elbistan", "Göksun", "Nurhak", "Onikişubat", "Pazarcık", "Türkoğlu"],
  "Karabük": ["Eflani", "Eskipazar", "Merkez", "Ovacık", "Safranbolu", "Yenice"],
  "Karaman": ["Ayrancı", "Başyayla", "Ermenek", "Kazımkarabekir", "Merkez", "Sarıveliler"],
  "Kars": ["Akyaka", "Arpaçay", "Digor", "Kağızman", "Merkez", "Sarıkamış", "Selim", "Susuz"],
  "Kastamonu": ["Abana", "Ağlı", "Araç", "Azdavay", "Bozkurt", "Cide", "Çatalzeytin", "Daday", "Devrekani", "Doğanyurt", "Hanönü", "İhsangazi", "İnebolu", "Küre", "Merkez", "Pınarbaşı", "Seydiler", "Şenpazar", "Taşköprü", "Tosya"],
  "Kayseri": ["Akkışla", "Bünyan", "Develi", "Felahiye", "Hacılar", "İncesu", "Kocasinan", "Melikgazi", "Özvatan", "Pınarbaşı", "Sarıoğlan", "Sarız", "Talas", "Tomarza", "Yahyalı", "Yeşilhisar"],
  "Kilis": ["Elbeyli", "Merkez", "Musabeyli", "Polateli"],
  "Kırıkkale": ["Bahşili", "Balışeyh", "Çelebi", "Delice", "Karakeçili", "Keskin", "Merkez", "Sulakyurt", "Yahşihan"],
  "Kırklareli": ["Babaeski", "Demirköy", "Kofçaz", "Lüleburgaz", "Merkez", "Pehlivanköy", "Pınarhisar", "Vize"],
  "Kırşehir": ["Akçakent", "Akpınar", "Boztepe", "Çiçekdağı", "Kaman", "Merkez", "Mucur"],
  "Kocaeli": ["Başiskele", "Çayırova", "Darıca", "Derince", "Dilovası", "Gebze", "Gölcük", "İzmit", "Kandıra", "Karamürsel", "Kartepe", "Körfez"],
  "Konya": ["Ahırlı", "Akören", "Akşehir", "Altınekin", "Beyşehir", "Bozkır", "Cihanbeyli", "Çeltik", "Çumra", "Derbent", "Derebucak", "Doğanhisar", "Emirgazi", "Ereğli", "Güneysınır", "Hadim", "Halkapınar", "Hüyük", "Ilgın", "Kadınhanı", "Karapınar", "Karatay", "Kulu", "Meram", "Sarayönü", "Selçuklu", "Seydişehir", "Taşkent", "Tuzlukçu", "Yalıhüyük", "Yunak"],
  "Kütahya": ["Altıntaş", "Aslanapa", "Çavdarhisar", "Domaniç", "Dumlupınar", "Emet", "Gediz", "Hisarcık", "Merkez", "Pazarlar", "Simav", "Şaphane", "Tavşanlı"],
  "Malatya": ["Akçadağ", "Arapgir", "Arguvan", "Battalgazi", "Darende", "Doğanşehir", "Doğanyol", "Hekimhan", "Kale", "Kuluncak", "Pütürge", "Yazıhan", "Yeşilyurt"],
  "Manisa": ["Ahmetli", "Akhisar", "Alaşehir", "Demirci", "Gölmarmara", "Gördes", "Kırkağaç", "Köprübaşı", "Kula", "Salihli", "Sarıgöl", "Saruhanlı", "Selendi", "Soma", "Şehzadeler", "Turgutlu", "Yunusemre"],
  "Mardin": ["Artuklu", "Dargeçit", "Derik", "Kızıltepe", "Mazıdağı", "Midyat", "Nusaybin", "Ömerli", "Savur", "Yeşilli"],
  "Mersin": ["Akdeniz", "Anamur", "Aydıncık", "Bozyazı", "Çamlıyayla", "Erdemli", "Gülnar", "Mezitli", "Mut", "Silifke", "Tarsus", "Toroslar", "Yenişehir"],
  "Muğla": ["Bodrum", "Dalaman", "Datça", "Fethiye", "Kavaklıdere", "Köyceğiz", "Marmaris", "Menteşe", "Milas", "Ortaca", "Seydikemer", "Ula", "Yatağan"],
  "Muş": ["Bulanık", "Hasköy", "Korkut", "Malazgirt", "Merkez", "Varto"],
  "Nevşehir": ["Acıgöl", "Avanos", "Derinkuyu", "Gülşehir", "Hacıbektaş", "Kozaklı", "Merkez", "Ürgüp"],
  "Niğde": ["Altunhisar", "Bor", "Çamardı", "Çiftlik", "Merkez", "Ulukışla"],
  "Ordu": ["Akkuş", "Altınordu", "Aybastı", "Çamaş", "Çatalpınar", "Çaybaşı", "Fatsa", "Gölköy", "Gülyalı", "Gürgentepe", "İkizce", "Kabadüz", "Kabataş", "Korgan", "Kumru", "Mesudiye", "Perşembe", "Ulubey", "Ünye"],
  "Osmaniye": ["Bahçe", "Düziçi", "Hasanbeyli", "Kadirli", "Merkez", "Sumbas", "Toprakkale"],
  "Rize": ["Ardeşen", "Çamlıhemşin", "Çayeli", "Derepazarı", "Fındıklı", "Güneysu", "Hemşin", "İkizdere", "İyidere", "Kalkandere", "Merkez", "Pazar"],
  "Sakarya": ["Adapazarı", "Akyazı", "Arifiye", "Erenler", "Ferizli", "Geyve", "Hendek", "Karapürçek", "Karasu", "Kaynarca", "Kocaali", "Pamukova", "Sapanca", "Serdivan", "Söğütlü", "Taraklı"],
  "Samsun": ["Alaçam", "Asarcık", "Atakum", "Ayvacık", "Bafra", "Canik", "Çarşamba", "Havza", "İlkadım", "Kavak", "Ladik", "Ondokuzmayıs", "Salıpazarı", "Tekkeköy", "Terme", "Vezirköprü", "Yakakent"],
  "Siirt": ["Baykan", "Eruh", "Kurtalan", "Merkez", "Pervari", "Şirvan", "Tillo"],
  "Sinop": ["Ayancık", "Boyabat", "Dikmen", "Durağan", "Erfelek", "Gerze", "Merkez", "Saraydüzü", "Türkeli"],
  "Sivas": ["Akıncılar", "Altınyayla", "Divriği", "Doğanşar", "Gemerek", "Gölova", "Gürun", "Hafik", "İmranlı", "Kangal", "Koyulhisar", "Merkez", "Suşehri", "Şarkışla", "Ulaş", "Yıldızeli", "Zara"],
  "Şanlıurfa": ["Akçakale", "Birecik", "Bozova", "Ceylanpınar", "Eyyübiye", "Halfeti", "Haliliye", "Harran", "Hilvan", "Karaköprü", "Siverek", "Suruç", "Viranşehir"],
  "Şırnak": ["Beytüşşebap", "Cizre", "Güçlükonak", "İdil", "Merkez", "Silopi", "Uludere"],
  "Tekirdağ": ["Çerkezköy", "Çorlu", "Ergene", "Hayrabolu", "Kapaklı", "Malkara", "Marmaraereğlisi", "Muratlı", "Saray", "Süleymanpaşa", "Şarköy"],
  "Tokat": ["Almus", "Artova", "Başçiftlik", "Erbaa", "Merkez", "Niksar", "Pazar", "Reşadiye", "Sulusaray", "Turhal", "Yeşilyurt", "Zile"],
  "Trabzon": ["Akçaabat", "Araklı", "Arsin", "Beşikdüzü", "Çarşıbaşı", "Çaykara", "Dernekpazarı", "Düzköy", "Hayrat", "Köprübaşı", "Maçka", "Of", "Ortahisar", "Pelitli", "Şalpazarı", "Sürmene", "Tonya", "Vakfıkebir", "Yomra"],
  "Tunceli": ["Çemişgezek", "Hozat", "Mazgirt", "Merkez", "Nazımiye", "Ovacık", "Pertek", "Pülümür"],
  "Uşak": ["Banaz", "Eşme", "Karahallı", "Merkez", "Sivaslı", "Ulubey"],
  "Van": ["Bahçesaray", "Başkale", "Çaldıran", "Çatak", "Edremit", "Erciş", "Gevaş", "Gürpınar", "İpekyolu", "Muradiye", "Özalp", "Saray", "Tuşba"],
  "Yalova": ["Altınova", "Armutlu", "Çiftlikköy", "Çınarcık", "Merkez", "Termal"],
  "Yozgat": ["Akdağmadeni", "Aydıncık", "Boğazlıyan", "Çandır", "Çayıralan", "Çekerek", "Kadışehri", "Merkez", "Saraykent", "Sarıkaya", "Şefaatli", "Sorgun", "Yenifakılı", "Yerköy"],
  "Zonguldak": ["Alaplı", "Çaycuma", "Devrek", "Ereğli", "Gökçebey", "Kilimli", "Kozlu", "Merkez"],
};

// Neighbourhood (Mahalle) data keyed as "City|District"
export const TURKEY_MAHALLELER: Record<string, string[]> = {
  // ─── İstanbul ───────────────────────────────────────────────
  "İstanbul|Adalar": ["Büyükada", "Heybeliada", "Burgazada", "Kınalıada"],
  "İstanbul|Arnavutköy": ["Arnavutköy Merkez", "Bolluca", "Haraçcı", "Taşoluk", "Yassıören"],
  "İstanbul|Ataşehir": ["Barbaros", "Çiftçiçeşmesi", "Ferhatpaşa", "İçerenköy", "İnönü", "Kayışdağı", "Küçükbakkalköy", "Mevlana", "Yenisahra"],
  "İstanbul|Avcılar": ["Ambarlı", "Cihangir", "Denizköşkler", "Firuzköy", "Gümüşpala", "Merkez", "Tahtakale", "Üniversite"],
  "İstanbul|Bağcılar": ["Bağlar", "Barbaros", "Demirkapı", "Fevzi Çakmak", "Güneşli", "Hürriyet", "İnönü", "Kazım Karabekir", "Kemalpaşa", "Kirazlı", "Merkez", "Yavuzselim", "Yıldıztepe"],
  "İstanbul|Bahçelievler": ["Bahçelievler", "Cumhuriyet", "Hürriyet", "Kocasinan", "Soğanlı", "Şirinevler", "Zafer"],
  "İstanbul|Bakırköy": ["Ataköy", "Cevizlik", "Kartaltepe", "Osmaniye", "Sakızağacı", "Yeşilköy", "Yeşilyurt", "Zuhuratbaba"],
  "İstanbul|Başakşehir": ["Bahçeşehir 1. Kısım", "Bahçeşehir 2. Kısım", "Başakşehir", "Kayabaşı", "Şahintepe"],
  "İstanbul|Bayrampaşa": ["Kartaltepe", "Kocatepe", "Muratpaşa", "Orta", "Rami Cuma", "Yenidoğan"],
  "İstanbul|Beşiktaş": ["Abbasağa", "Akatlar", "Arnavutköy", "Balmumcu", "Bebek", "Dikilitaş", "Etiler", "Gayrettepe", "Kuruçeşme", "Levent", "Mecidiyeköy", "Muradiye", "Nisbetiye", "Ortaköy", "Sinanpaşa", "Ulus", "Vişnezade", "Yıldız"],
  "İstanbul|Beykoz": ["Anadoluhisarı", "Beykoz Merkez", "Çubuklu", "Göksu", "Paşabahçe", "Polonezköy", "Riva"],
  "İstanbul|Beylikdüzü": ["Barış", "Büyükşehir", "Cumhuriyet", "Dereağzı", "Gürpınar", "Kavaklı", "Marmara"],
  "İstanbul|Beyoğlu": ["Azapkapı", "Bülbül", "Cihangir", "Fındıklı", "Galata", "Hacıahmet", "Hüseyinağa", "Karaköy", "Katip Mustafa Çelebi", "Kurtuluş", "Piripaşa", "Sütlüce", "Tarlabaşı", "Tomtom", "Yenişehir"],
  "İstanbul|Büyükçekmece": ["Büyükçekmece Merkez", "Güzelce", "Kumburgaz", "Pınar"],
  "İstanbul|Çatalca": ["Çatalca Merkez", "Ferhatpaşa", "Karacaköy"],
  "İstanbul|Çekmeköy": ["Çekmeköy Merkez", "Hamidiye", "Maksudiye", "Nişantepe", "Reşadiye"],
  "İstanbul|Esenler": ["Birlik", "Fatih", "Fevziçakmak", "Havaalanı", "Menderes", "Nenehatun", "Oruçreis", "Turgut Reis", "Yıldız"],
  "İstanbul|Esenyurt": ["Ardıçlı", "Esenyurt Merkez", "Fatih", "Güvenevler", "Güzelyurt", "İnönü", "Mehterçeşme", "Pınar", "Saadetdere"],
  "İstanbul|Eyüpsultan": ["Alibeyköy", "Çırçır", "Defterdar", "Düğmeciler", "Göktürk", "Güzeltepe", "İslambey", "Nişanca", "Rami Cuma", "Silahtarağa"],
  "İstanbul|Fatih": ["Aksaray", "Atışalanı", "Beyazıt", "Çarşamba", "Cibali", "Kocamustafapaşa", "Molla Gürani", "Nişanca", "Sarıdemir", "Süleymaniye", "Zeyrek"],
  "İstanbul|Gaziosmanpaşa": ["Bağlarbaşı", "Barbaros", "Fevzi Çakmak", "Güneştepe", "Hürriyet", "Karadeniz", "Karlıtepe", "Kazım Karabekir", "Mimar Sinan", "Sarıgöl", "Yenidoğan"],
  "İstanbul|Güngören": ["Abdurrahmangazi", "Ak", "Akıncılar", "Güneştepe", "Haznedar", "Merkez", "Tozkoparan"],
  "İstanbul|Kadıköy": ["Acıbadem", "Bostancı", "Caddebostan", "Caferağa", "Erenköy", "Fenerbahçe", "Fikirtepe", "Göztepe", "Koşuyolu", "Merdivenköy", "Moda", "Osmanağa", "Rasimpaşa", "Suadiye", "Zühtüpaşa"],
  "İstanbul|Kağıthane": ["Gürsel", "Hamidiye", "Harmantepe", "Merkez", "Nurtepe", "Ortabayır", "Seyrantepe", "Yahyakemal"],
  "İstanbul|Kartal": ["Çavuşoğlu", "Cevizli", "Eğitim", "Gümüşpınar", "Hürriyet", "İstasyon", "Kordonboyu", "Orhantepe", "Soğanlık", "Topselvi", "Yakacık"],
  "İstanbul|Küçükçekmece": ["Atakent", "Cennet", "Fatih", "Halkalı", "İnönü", "Kanarya", "Kartaltepe", "Mehmet Akif", "Söğütlü", "Yarımburgaz"],
  "İstanbul|Maltepe": ["Altıntepe", "Bağlarbaşı", "Başıbüyük", "Cevizli", "Fındıklı", "İdealtepe", "Zümrütevler"],
  "İstanbul|Pendik": ["Batı", "Doğu", "Güzelyalı", "Kurtköy", "Orta", "Velibaba", "Yenişehir"],
  "İstanbul|Sancaktepe": ["Emek", "Eyüpsultan", "Kaynarca", "Samandıra", "Sancaktepe Merkez"],
  "İstanbul|Sarıyer": ["Bahçeköy", "Baltalimanı", "Ferahevler", "Garipçe", "İstinye", "Kireçburnu", "Pınar", "Reşitpaşa", "Rumelihisarı", "Tarabya", "Uskumruköy", "Yenimahalle", "Zekeriyaköy"],
  "İstanbul|Şile": ["Şile Merkez", "Ağva"],
  "İstanbul|Şişli": ["Bozkurt", "Büyükdere", "Camiikebir", "Cumhuriyet", "Ergenekon", "Esentepe", "Feriköy", "Fulya", "Gülbahar", "Halaskargazi", "Harbiye", "Kuştepe", "Mecidiyeköy", "Nişantaşı", "Teşvikiye", "Çağlayan"],
  "İstanbul|Silivri": ["Alibey", "Büyüksinekli", "Çantık", "Çeşmeköy", "Silivri Merkez"],
  "İstanbul|Sultangazi": ["Cebeci", "Cumhuriyet", "Habibler", "Malkoçoğlu", "Sultançiftliği"],
  "İstanbul|Sultanbeyli": ["Sultanbeyli Merkez", "Yenidoğan"],
  "İstanbul|Tuzla": ["Aydınlı", "Cami", "İçmeler", "Mescit", "Postane", "Tuzla Merkez"],
  "İstanbul|Ümraniye": ["Çakmak", "Elmalıkent", "Esatpaşa", "İnkılap", "Mimar Sinan", "Parseller"],
  "İstanbul|Üsküdar": ["Acıbadem", "Ahmediye", "Altunizade", "Bağlarbaşı", "Beylerbeyi", "Burhaniye", "Çengelköy", "Doğancılar", "Kandilli", "Kısıklı", "Mimar Sinan", "Selamiali", "Selimiye", "Sultantepe", "Ünalan"],
  "İstanbul|Zeytinburnu": ["Çırpıcı", "Gökalp", "Kazlıçeşme", "Merkezefendi", "Nuripaşa", "Sümer", "Telsiz", "Veliefendi", "Yenidoğan"],

  // ─── Ankara ─────────────────────────────────────────────────
  "Ankara|Altındağ": ["Atıfbey", "Çinçin", "Hüseyingazi", "İsmetpaşa", "Ulucanlar", "Zübeyde Hanım"],
  "Ankara|Çankaya": ["Ahlatlıbel", "Beytepe", "Birlik", "Bülbülderesi", "Çayyolu", "Dikmen", "Emek", "Hoşdere", "İncek", "Kavaklıdere", "Kızılay", "Küçükesat", "Mebusevleri", "Olgunlar", "Oran", "Öveçler", "Yaşamkent", "Yıldız"],
  "Ankara|Etimesgut": ["Elvankent", "Eryaman", "Pınarbaşı", "Şaşmaz"],
  "Ankara|Gölbaşı": ["Abadiye", "Bağlıca", "Gölbaşı Merkez", "Tuluntaş"],
  "Ankara|Keçiören": ["Bağlum", "Etlik", "Güçlükaya", "Kalaba", "Kuşcağız", "Ovacık", "Şenyuva"],
  "Ankara|Mamak": ["Abidinpaşa", "Balkayası", "Demirlibahçe", "Karşıyaka", "Kusunlar", "Saimekadın"],
  "Ankara|Pursaklar": ["İvedik", "Pursaklar Merkez", "Saray"],
  "Ankara|Sincan": ["Ayyıldız", "Fatih", "Gazi", "İsmet İnönü", "Plevne", "Saraycık"],
  "Ankara|Yenimahalle": ["Demetevler", "Doğukent", "Ergazi", "İvedik", "Kartaltepe", "Ostim", "Şentepe"],

  // ─── İzmir ──────────────────────────────────────────────────
  "İzmir|Balçova": ["Balçova Merkez", "İnciraltı", "Teleferik"],
  "İzmir|Bayraklı": ["Bayraklı Merkez", "Çamkule", "Kazımdirik", "Osmangazi", "Poligon", "Yamanlar"],
  "İzmir|Bornova": ["Atatürk", "Çamdibi", "Doğanlar", "Evka", "Gazi", "Kazımdirik", "Naldöken", "Yeşilova"],
  "İzmir|Buca": ["Adatepe", "Çamlıkule", "Egekent", "Emrez", "Kaynaklar", "Kozağaç", "Kuyu", "Merkez"],
  "İzmir|Çiğli": ["Balatçık", "Çiğli Merkez", "Küçükçiğli", "Sasalı"],
  "İzmir|Gaziemir": ["Aktepe", "Gaziemir Merkez", "Onur"],
  "İzmir|Güzelbahçe": ["Güzelbahçe Merkez", "Yelki"],
  "İzmir|Karabağlar": ["Bozyaka", "Güzelyalı", "Işıkkent", "Mevlana", "Yenialemdar"],
  "İzmir|Karşıyaka": ["Bostanlı", "Donanmacı", "Hasan Tahsin", "Mavişehir", "Nergiz", "Oya"],
  "İzmir|Konak": ["Alsancak", "Basmane", "Çankaya", "Hatay", "Kahramanlar", "Kültürpark", "Mithatpaşa", "Mürselpaşa", "Türkocağı"],
  "İzmir|Narlıdere": ["Narlıdere Merkez", "Site"],

  // ─── Bursa ───────────────────────────────────────────────────
  "Bursa|Nilüfer": ["Ataevler", "Balat", "Bademli", "Beşevler", "Fethiye", "Görükle", "Hürriyet", "İhsaniye"],
  "Bursa|Osmangazi": ["Doğanbey", "Fethiye", "Heykel", "Hürriyet", "İnegöl Mah", "Maksem", "Santral", "Soğanlı"],
  "Bursa|Yıldırım": ["Cumalıkızık", "Doburca", "Emir Sultan", "Hanönü", "Millet", "Üçevler"],

  // ─── Antalya ─────────────────────────────────────────────────
  "Antalya|Kepez": ["Altınkum", "Arapsuyu", "Çağlayan", "Göksu", "Hurma", "Sütçüler", "Varsak"],
  "Antalya|Konyaaltı": ["Konyaaltı Merkez", "Liman", "Sarısu", "Uncalı"],
  "Antalya|Muratpaşa": ["Bahçelievler", "Çağlayan", "Fener", "Güzelbağ", "Kışla", "Sinan", "Üçgen", "Yeşilbahçe"],

  // ─── Adana ───────────────────────────────────────────────────
  "Adana|Çukurova": ["Çınarlı", "Denizli", "Kurttepe", "Toros", "Yeşilbağlar"],
  "Adana|Seyhan": ["Emek", "Kızılay", "Kurtuluş", "Merkez", "Reşatbey", "Yeşilyurt"],
  "Adana|Yüreğir": ["Beyazevler", "Denizli", "Fatih", "Karataş", "Toros"],

  // ─── Gaziantep ───────────────────────────────────────────────
  "Gaziantep|Şahinbey": ["Bey", "Çıksorut", "Düztepe", "Gazimuhtarpaşa", "İncilipınar", "Mücahitler", "Suburcu"],
  "Gaziantep|Şehitkamil": ["Bağlarbaşı", "Çıksorut", "Fevziçakmak", "Güvenevler", "Karataş", "Nizip Yolu", "Osmanbey"],

  // ─── Konya ───────────────────────────────────────────────────
  "Konya|Karatay": ["Fevzi Çakmak", "Karatay Merkez", "Musalla", "Sahibiata", "Topraklık"],
  "Konya|Meram": ["Aşkan", "Çukurbağ", "Gödene", "Meram Merkez", "Yazır"],
  "Konya|Selçuklu": ["Bosna-Hersek", "Dikilitaş", "Hüseyinşeyh", "Kılıçarslan", "Sarayönü", "Selçuklu Merkez"],

  // ─── Mersin ──────────────────────────────────────────────────
  "Mersin|Akdeniz": ["Çay", "Çeşmeli", "Kışla", "Nusratiye", "Palmiye"],
  "Mersin|Mezitli": ["Davultepe", "Kazanlı", "Kuyuluk", "Mezitli Merkez"],
  "Mersin|Toroslar": ["Bahşiş", "Güneykent", "Kocavilayet", "Mut Yolu", "Toroslar Merkez"],
  "Mersin|Yenişehir": ["Bahçe", "Camişerif", "Demirtaş", "Gazi Mustafa Kemal", "Nusratiye"],

  // ─── Kayseri ─────────────────────────────────────────────────
  "Kayseri|Kocasinan": ["Alpaslan", "Hürriyet", "İstasyon", "Kocasinan Merkez", "Sivas Yolu"],
  "Kayseri|Melikgazi": ["Anbar", "Bahçelievler", "Gesi", "Melikgazi Merkez", "Sümer"],
  "Kayseri|Talas": ["Anayurt", "Talas Merkez", "Yıldıztepe"],

  // ─── Diyarbakır ──────────────────────────────────────────────
  "Diyarbakır|Bağlar": ["Bağlar Merkez", "Çarıklı", "İskenderpaşa", "Karacadağ", "Peyas"],
  "Diyarbakır|Kayapınar": ["Diclekent", "Kayapınar Merkez", "Üçkuyular", "Üçyol"],
  "Diyarbakır|Sur": ["Ali Paşa", "Cemal Yılmaz", "Fatihpaşa", "Lalebey", "Ziya Gökalp"],
  "Diyarbakır|Yenişehir": ["Aziziye", "Çarıklı", "Melikahmet", "Şehitlik", "Yenişehir Merkez"],

  // ─── Trabzon ─────────────────────────────────────────────────
  "Trabzon|Ortahisar": ["Boztepe", "Fetihtepe", "İskenderpaşa", "Kemerkaya", "Ortahisar Merkez", "Pelitli"],

  // ─── Samsun ──────────────────────────────────────────────────
  "Samsun|Atakum": ["Atakum Merkez", "Belediye Evleri", "Çarşamba Yolu", "Gülbahçe"],
  "Samsun|Canik": ["Canik Merkez", "Esenevler", "Gazi", "Nergiz"],
  "Samsun|İlkadım": ["Baruthane", "Çiftlik", "İlkadım Merkez", "Kadıköy", "Kökçüoğlu"],

  // ─── Kocaeli ─────────────────────────────────────────────────
  "Kocaeli|İzmit": ["Bahçelievler", "Durhasan", "İzmit Merkez", "Körfez", "Orhan"],
  "Kocaeli|Gebze": ["Aydınlı", "Çayırova", "Gebze Merkez", "Güzeller", "İhsaniye"],
  "Kocaeli|Kartepe": ["Arslanbey", "Derbent", "Hisareyn", "Kartepe Merkez"],

  // ─── Eskişehir ───────────────────────────────────────────────
  "Eskişehir|Odunpazarı": ["Akarbaşı", "Büyükdere", "Emek", "Kurtuluş", "Odunpazarı Merkez", "Şirintepe"],
  "Eskişehir|Tepebaşı": ["Alanönü", "Hoşnudiye", "Tepebaşı Merkez", "Yıldıztepe"],

  // ─── Hatay ───────────────────────────────────────────────────
  "Hatay|Antakya": ["Antakya Merkez", "Armutlu", "Defne", "Narlıca"],
  "Hatay|İskenderun": ["Güzelce", "İskenderun Merkez", "Karaçay", "Tüysüz"],

  // ─── Şanlıurfa ───────────────────────────────────────────────
  "Şanlıurfa|Eyyübiye": ["Eyyübiye Merkez", "Fırat", "Karaköprü"],
  "Şanlıurfa|Haliliye": ["Bediüzzaman", "Haliliye Merkez", "Yenişehir"],
  "Şanlıurfa|Karaköprü": ["Karaköprü Merkez", "Nevzat Pekin", "Şanlıurfa Yolu"],
};

export const TURKISH_BANKS = [
  "Ziraat Bankası",
  "İş Bankası",
  "Garanti BBVA",
  "Yapı Kredi",
  "Akbank",
  "Halkbank",
  "VakıfBank",
  "QNB Finansbank",
  "TEB – Türk Ekonomi Bankası",
  "DenizBank",
  "ING Bank Türkiye",
  "HSBC Türkiye",
  "Odeabank",
  "Şekerbank",
  "Türkiye Finans Katılım Bankası",
  "Kuveyt Türk Katılım Bankası",
  "Albaraka Türk",
  "Ziraat Katılım Bankası",
  "Vakıf Katılım Bankası",
  "Emlak Katılım Bankası",
  "Burgan Bank",
  "ICBC Turkey Bank",
];
